version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
      - .:/app

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - tests_node_modules:/app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

volumes:
  node_modules:
  tests_node_modules: